project:
  type: website

execute:
  freeze: auto

website:
  title: "Dan Nolte"
  image: photos/headshot.png
  navbar:
    background: "#F78734"
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Words
        href: content/blog/overview.qmd
      - text: Projects
        href: content/projects/projects.qmd
      - text: Resume
        href: content/resume/resume.pdf

  sidebar:
    - title: "Words"
      style: "docked"
      background: light
      contents:
        - content/blog/overview.qmd
        - content/blog/identity.qmd

    - title: Projects
      contents:
        - content/projects/projects.qmd

    - title: Resume
      contents:
        - content/resume/resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



